src/main/java/app/model/entity/Publication.java
package app.model.entity;


import javax.validation.constraints.Max;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Objects;


public class Publication implements Comparable {
    private String id;
    @NotNull(message = "The article should have a title")
    @Max(150)
    private String title;
    private String text;
    private String image;
    private boolean published;
    private Date datePublication;
    private Date updateDate;
    private String user_id;
    @Max(300)
    private String description;
    @NotNull
    private String titleImage;

    public Publication() {
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    public String getTitleImage() {
        return titleImage;
    }

    public void setTitleImage(String titleImage) {
        this.titleImage = titleImage;
    }

    @NotNull
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public boolean isPublished() {
        return published;
    }

    public void setPublished(boolean published) {
        this.published = published;
    }

    @NotNull
    public Date getDatePublication() {

        return datePublication;
    }


    public void setDatePublication(Date datePublication) {
        this.datePublication = datePublication;

    }

    public Date getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    @NotNull
    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getSimpleDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMMM Y", Locale.ENGLISH);
        if (updateDate == null) {
            return sdf.format(datePublication);
        } else return sdf.format(updateDate);
    }

    @Override
    public String toString() {
        return "Publication{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", text='" + text + '\'' +
                ", image='" + image + '\'' +
                ", published=" + published +
                ", datePublication=" + datePublication +
                ", updateDate=" + updateDate +
                ", user_id=" + user_id +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Publication that = (Publication) o;
        return id == that.id &&
                published == that.published &&
                user_id == that.user_id &&
                Objects.equals(title, that.title) &&
                Objects.equals(text, that.text) &&
                Objects.equals(image, that.image) &&
                Objects.equals(datePublication, that.datePublication) &&
                Objects.equals(updateDate, that.updateDate);
    }

    @Override
    public int hashCode() {

        return Objects.hash(id, title, text, image, published, datePublication, updateDate, user_id);
    }

    @Override
    public int compareTo(Object o) {
        Date last = null;
        Date lastThis = null;
        Publication publ = (Publication) o;
        last = publ.getUpdateDate() != null ? publ.getUpdateDate() : publ.getDatePublication();
        lastThis = this.getUpdateDate() != null ? this.getUpdateDate() : this.getDatePublication();
        if (lastThis.getTime() != last.getTime())
            return lastThis.getTime() > last.getTime() ? -1 : 1;
        else return 0;
    }
}

src/main/java/app/controller/servlets/AddPostServlet.java
package app.controller.servlets;

import app.model.dao.PublicationDAO;
import app.model.dao.UserDAO;
import app.model.entity.Publication;
import app.model.entity.User;


import org.apache.log4j.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;


@MultipartConfig
@WebServlet(urlPatterns = "/addPost")
public class AddPostServlet extends HttpServlet {

    private static final Logger logger = Logger.getLogger(AddPostServlet.class);

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        HttpSession session = req.getSession();
        PublicationDAO dao = new PublicationDAO();
        File uploads = new File(req.getServletContext().getRealPath("/content"));

        req.setCharacterEncoding("UTF8");
        try {
            final String login = (String) session.getAttribute("login");
            final User user = new UserDAO().getUser(login);
            final String title = req.getParameter("title");
            final String description = req.getParameter("description");
            final String text = req.getParameter("text");
            final boolean isDash = req.getParameter("dash") == null;
            Publication publication = new Publication();

            Part filePart = req.getPart("image");
            String fileName = Paths.get(filePart.getSubmittedFileName()).getFileName().toString();
            if (fileName.equals("")) {
                publication.setImage("");
            } else {
                String preffix = fileName.split("[.]")[0];
                String suffix = "." + fileName.split("[.]")[1];
                File file = new File(uploads, preffix + suffix);

                try (InputStream input = filePart.getInputStream()) {
                    Files.copy(input, file.toPath(), StandardCopyOption.REPLACE_EXISTING);
                }
                publication.setImage(file.getName());
            }


            Part filePartTI = req.getPart("titleImage");
            String fileNameTI = Paths.get(filePartTI.getSubmittedFileName()).getFileName().toString();
            if (fileNameTI.equals("")) {
                publication.setTitleImage("image/pic_blog_post_1_1.jpg");
            } else {
                String preffixTI = fileNameTI.split("[.]")[0];
                String suffixTI = "." + fileNameTI.split("[.]")[1];
                File fileTI = new File(uploads, preffixTI + suffixTI);
                try (InputStream input = filePartTI.getInputStream()) {
                    Files.copy(input, fileTI.toPath(), StandardCopyOption.REPLACE_EXISTING);
                }
                publication.setTitleImage(fileTI.getName());

                publication.setUser_id(user.getId());
                publication.setText(text);
                publication.setTitle(title);
                publication.setDescription(description);
                publication.setPublished(isDash);
                dao.addPublication(publication, user);
            }


           req.getRequestDispatcher("/userPage.jsp").forward(req,resp);
            logger.info("User"+login+" was added post - "+title);
        } catch (ClassNotFoundException e) {
            logger.error("ClassNotFoundException in AddPostServlet");
         logger.error(e.getMessage());
        }
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        req.getRequestDispatcher("/view/addPostForm.jsp").forward(req,resp);
    }
}

src/main/java/app/controller/servlets/ChangeUserDataServlet.java
package app.controller.servlets;

import app.model.dao.UserDAO;
import app.model.entity.User;

import org.apache.log4j.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;


@WebServlet(urlPatterns = "/changeUserData")
public class ChangeUserDataServlet extends HttpServlet {
    private static final Logger logger = Logger.getLogger(ChangeUserDataServlet.class);

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        final String login = (String) req.getSession().getAttribute("login");
        final String newName = req.getParameter("newName");
        final String newPassword = req.getParameter("newPassword");
        UserDAO dao = new UserDAO();
        try {
            User user = dao.getUser(login);
            user.setName(newName);
            user.setPassword(newPassword);
            dao.updateUserName(user);
            dao.updateUserPassword(user);
            req.getSession().setAttribute("name", newName);
            req.getSession().setAttribute("password", newPassword);

            doGet(req, resp);
            logger.info("The user "+login+" has edited his profile");
        } catch (ClassNotFoundException e) {
            logger.error("ClassNotFoundException in ChangeUserDataServlet");
        }
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        final String name = (String) req.getSession().getAttribute("name");
        req.setAttribute("name", name);
        req.getRequestDispatcher("view/homePage.jsp").forward(req, resp);
    }
}

src/main/java/app/controller/servlets/DashServlet.java
package app.controller.servlets;

import app.model.dao.PublicationDAO;
import app.model.dao.UserDAO;
import app.model.entity.Publication;
import app.model.entity.User;

import org.apache.log4j.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Collections;
import java.util.concurrent.CopyOnWriteArrayList;

@WebServlet(urlPatterns = "/dash")
public class DashServlet extends HttpServlet {
    private static final Logger logger = Logger.getLogger(DashServlet.class);

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            final String name = (String) req.getSession().getAttribute("name");
            final User user = new UserDAO().getUser((String) req.getSession().getAttribute("login"));
            req.setAttribute("name", name);
            PublicationDAO dao = new PublicationDAO();
            CopyOnWriteArrayList<Publication> publications = dao.getAllPublications(user);
            Collections.sort(publications);
            req.setAttribute("list", publications);
            req.getRequestDispatcher("/view/dash.jsp").forward(req, resp);
            logger.info("the draft was loaded");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            logger.error("ClassNotFoundException in DashServlet");
        } catch (SQLException e) {
            e.printStackTrace();
            logger.error("SQLExeption in DashServlet");
        }

    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        final String id = req.getParameter("id");
        PublicationDAO dao = new PublicationDAO();

        try {
            Publication publication = dao.getPublication(id);
            publication.setPublished(true);
            dao.updatePublication(publication);
            req.getRequestDispatcher("/userPage.jsp").forward(req, resp);
            logger.info("The post was moved from the draft");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            logger.error("ClassNotFoundException in DashServlet");
        } catch (SQLException e) {
            e.printStackTrace();
            logger.error("SQLException e in DashServlet :Possible problems with the connection");
        }
    }
}

src/main/java/app/controller/servlets/DeletePostServlet.java
package app.controller.servlets;

import app.model.dao.PublicationDAO;

import app.model.entity.Publication;
import org.apache.log4j.Logger;


import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.SQLException;

@WebServlet(urlPatterns = "/deletePost")
public class DeletePostServlet extends HttpServlet {
    private static final Logger logger = Logger.getLogger(DeletePostServlet.class);
    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        final String id = req.getParameter("id");
        try {
            PublicationDAO dao = new PublicationDAO();
            Publication publication = dao.getPublication(id);
            dao.deletePublication(publication);
            if (req.getParameter("isDash") != null) {
                resp.sendRedirect("/dash");
            } else {
                req.getRequestDispatcher("/userPage.jsp").forward(req, resp);
            }
       logger.info("The post"+id+"was deleted");
        } catch (SQLException e) {
            e.printStackTrace();
        logger.error("SQLException in DeletePostServlet:Possible problems with the connection");
        } catch (ClassNotFoundException e) {
            logger.error(e.getMessage());
        }
    }


}

src/main/java/app/controller/servlets/EnterServlet.java
package app.controller.servlets;

import app.model.dao.UserDAO;
import app.model.utils.HashPassword;
import org.apache.log4j.Logger;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import java.io.IOException;


@WebServlet(urlPatterns = "/enter")
public class EnterServlet extends HttpServlet {
    private static final Logger logger = Logger.getLogger(EnterServlet.class);

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.sendRedirect(req.getContextPath()+ "/userPage.jsp");

    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        final String login = req.getParameter("login");
        final String password = req.getParameter("password");
        HttpSession session = req.getSession();
        UserDAO dao = new UserDAO();
        try {
            if (dao.isExistUser(login) && HashPassword.passwordCheck(password,dao.getUser(login))) {
                session.setAttribute("name", new UserDAO().getUser(login).getName());
                session.setAttribute("login", login);
//                session.setAttribute("password", password);
                logger.info("User " + login + " log in");
                doGet(req, resp);
            } else {
                req.setAttribute("message", "Invalid password or login!");
                req.getRequestDispatcher("/").forward(req, resp);
                logger.info("The user could not log in");
            }
        } catch (ClassNotFoundException e) {

            logger.error("ClassNotFoundException in EnterServlet"+e.getMessage());
        }
    }
}

src/main/java/app/controller/servlets/IndexServlet.java
package app.controller.servlets;

import app.model.dao.PublicationDAO;
import app.model.entity.Publication;
import org.apache.log4j.Logger;


import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Collections;
import java.util.concurrent.CopyOnWriteArrayList;

@WebServlet(urlPatterns = "")
public class IndexServlet extends HttpServlet {
    private static final Logger logger = Logger.getLogger(IndexServlet.class);

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        doGet(req,resp);
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        try {
            PublicationDAO dao = new PublicationDAO();
            CopyOnWriteArrayList<Publication> publications = dao.getAll();
            Collections.sort(publications);
            req.setAttribute("listAll", publications);
            req.getRequestDispatcher("index.jsp").forward(req, resp);
            logger.info("First page was loaded");
        } catch (SQLException e) {
            logger.error("SQLException in IndexServlet:Possible problems with the connection"+e.getMessage());
        } catch (ClassNotFoundException e) {
          logger.error(e.getMessage());
        }

    }
}

src/main/webapp/index.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/style">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!--[if lt IE 9]>
    <script type="text/javascript" src="layout/plugins/html5.js"></script>
    <![endif]-->
    <link rel="stylesheet" href="layout/style.css" type="text/css">
    <script type="text/javascript" src="layout/js/jquery.js"></script>
    <script type="text/javascript" src="layout/js/plugins.js"></script>
    <script type="text/javascript" src="layout/js/main.js"></script>
</head>
<body>
<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <a class="btn btn-dark" href="${pageContext.request.contextPath}/registration" id="Registration"
           name="registration">Sign Up</a>

        <details class="btn btn-dark btn-sm" style="outline: none ">
            <summary>Log in</summary>

            <form id="login" method="post" action="${pageContext.request.contextPath}/enter">
                <input type="text" name="login" placeholder="Enter your login">
                <input type="password" name="password" placeholder="Enter your password"/>
                <input type="submit" value="Enter" class="btn btn-success btn-sm"/>
            </form>

            <p style="color: red"><c:out value="${message}"/></p>

        </details>
        <form style="margin-left: 61rem" class="form-inline" method="post"
              action="${pageContext.request.contextPath}/search">
            <input type="search" class="form-control mr-sm-2" name="search">
            <input type="image" src="${pageContext.request.contextPath}/layout/images/icon_search_1.png"/>
        </form>
    </nav>


</div>
<div id="logo" style=""><p><img src="image/logo.png"></p>
</div>
<%--<div id="category"><p >Trave Music Image History Sport</p></div>--%>
<div id="content" class="">
    <div class="inner">
        <div class="block_slider_type_1 general_not_loaded">
            <div id="slider" class="slider flexslider">
                <ul class="slides">
                    <c:forEach var="pub1" items="${listAll}">
                        <c:if test="${pub1.published==true}">
                            <li>
                                <div style="max-width: 60rem;max-height: 30rem;display: block;background-image: url(${pageContext.request.contextPath}/layout/images/back_roll.jpg); ">
                                    <img src="content/${pub1.titleImage}" alt=""
                                         style="height:30rem;; width: auto;margin-left:auto;margin-right: auto;display: block;"/>
                                    <div class="animated_item text_1_1" data-animation-show="fadeInUp"
                                         data-animation-hide="fadeOutDown"></div>
                                    <div class="animated_item text_1_2" data-animation-show="fadeInUp"
                                         data-animation-hide="fadeOutDown"><c:out value="${pub1.title}"/></div>
                                    <div class="animated_item text_1_3" data-animation-show="fadeInUp"
                                         data-animation-hide="fadeOutDown"><a
                                            href="${pageContext.request.contextPath}/postPage?id=${pub1.id}"
                                            class="general_button_type_1">Read More</a>
                                    </div>
                                </div>
                            </li>

                        </c:if>
                    </c:forEach>
                </ul>

            </div>

            <script type="text/javascript">
                jQuery(function () {
                    init_slider_1('#slider');
                });
            </script>
        </div>
    </div>
</div>

<div class="block_general_title_1 w_margin_1">
    <h1>Latest Posts</h1>
</div>

<div class="block_posts type_1 type_sort general_not_loaded">

    <div class="posts" style="margin-left: 5.5rem;" id="con">

        <c:forEach var="pub1" items="${listAll}">
            <c:if test="${pub1.published==true}">


                <article class="post_type_1">
                    <div class="feature">
                        <div class="image">
                            <c:if test="${pub1.titleImage!=''}">

                                <a href="${pageContext.request.contextPath}/postPage?id=${pub1.id}">
                                    <img src="content/${pub1.titleImage}">
                                    <span class="hover"> <h3><p
                                            style="color: white;background: rgba(0, 0, 0, 0.7); padding: 10px;"><c:out
                                            value="${pub1.title}"/><br/></p></h3></span></a>

                            </c:if>
                            <script>
                                $(function () {
                                    $("h3").wrapInner("<span>");
                                    $("h3 br").before("<span class='spacer'>")
                                        .after("<span class='spacer'>");
                                });</script>


                        </div>
                    </div>

                    <div class="content">
                        <div class="info">

                            <div class="date"><c:out value="${pub1.simpleDate}"/></div>
                            <div class="stats">


                            </div>
                        </div>
                        <div class="title">
                            <a href="${pageContext.request.contextPath}/postPage?id=${pub1.id}"><c:out
                                    value="${pub1.description}"/></a>
                        </div>
                    </div>
                </article>
            </c:if>
        </c:forEach>

    </div>
    <div class="controls">
        <a href="#" id="button_load_more" data-target=".block_posts.type_sort .posts" class="load_more_1"><span>Load more posts</span></a>
    </div>
</div>


</body>
</html>